### ISSUE TITLE
GA 和评论 repo 没改

### ISSUE THREAD

**Issue by ouuan** [pwwq/pwwq.github.io#1]
出现在我的 GA 排行榜我才发现 :new_moon_with_face: 

![图片](https://user-images.githubusercontent.com/30581822/100537668-496e8e80-3265-11eb-8972-123b586fe52a.png)

不知道还有没有其它没改的..仔细检查一下吧，或者直接搞个新的，不要基于我的搞..

**Comment by pwwq** [comment]
改好了，感谢大佬提供的改版主题，代码复制,全局搜索这2个很实用

**Comment by ouuan** [comment]
等等你的评论 repo 好像还是 ouuan/blog-comments

**Comment by pwwq** [comment]
![SAVE_20201206_020916](https://user-images.githubusercontent.com/70942468/101260072-15fd9980-3768-11eb-85eb-3d615b3fb3f7.jpg)

**Comment by ouuan** [comment]
https://github.com/pwwq/hugo-theme-even/blob/709f99f89a4ed96b5adf0d84edc1dfa4c35de2a6/layouts/partials/comments.html#L133

更新一下 even 吧，最新版这里都是 `https://github.com/{{ .Site.Params.utterances.owner }}/{{ .Site.Params.utterances.repo }}/issues`.
